name: Build and Zip Chrome Extension

on:
  workflow_dispatch:

jobs:
  build:
    env: 
      RUNNER_TOOL_CACHE: /toolcache
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
 
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
 
      - name: Install dependencies
        run: yarn
 
      - name: Build Chrome
        run: yarn build:chrome

      - name: Upload Chrome extension artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vite-web-extension-chrome
          path: dist_chrome